<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise.prototype.then 方法</title>
</head>

<body>
    <script>
        //  创建一个 Promise 对象
        const p = new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve('成功')
                }, 1000)
            })
            //  调用 。then（） 方法， 参数是2个回调函数， 分别处理成功，失败情况
            //  1. 如果回电函数中返回的结果是 非 promise 类型的属性，状态为成功，且返回值就是对象的成功值
            //  
        const result = p.then(function(value) {
            console.log(value)
                // 1。 返回 非 promise 类型的属性
                // return 23;
                //  2. 如果返回的是一个promise 对象； 
                // return new Promise((resolve, reject) => {
                //     reject('出错了') // 返回的值就是错误，回调 fn（reason) 就输出 “出错了”
                // })
                // return new Promise((resolve, reject) => {
                //     resolve('得到了得到了') // 这样返回状态是成功，
                // })
                // 3. 抛出错误
            throw new Error('错了，错了，不好了') // 就会调用后面的 fun（reason) { } 输出： '错了，错了，不好了'， z这个promise 状态就是rejected
        }, function(reason) {
            console.warn(reason)
        })
        console.log(result) // 返回结果也是一个promise 对象，status 是 resolved, then方法的返回结果是promise 对象，对象状态由回调函数的执行结果决定；

        //  .then() 是可以链式调用的。指定回调的时候也可以只指定一个 比如成功后的回调，
        p.then(value => {}, reason => {}).then(value => {}, reason => {})
    </script>
</body>

</html>